workflows:
  andorid:
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Switch to a specific version of Cordova
        script: |
          set -e # exit on first failed command
          
          cvm install 9.0.0
          cvm use 9.0.0
      - name: Add Android platform
        script: |
          set -e # exit on first failed command

          cordova platform remove android --nosave
          cordova platform add android --confirm --no-interactive --noresources
      - name: Build Android release
        script: |
          set -e # exit on first failed command

          cordova build android --no-interactive
    artifacts:
      - /Users/builder/clone/platforms/android/app/build/outputs/apk/debug/app-debug.apk
    environment:
      groups:
        - discord
triggering:
  events:                       # List the events that trigger builds
    - push
    - pull_request
  branch_patterns:              # Include or exclude watched branches
    - pattern: 'app'
      include: true
      source: true
    - pattern: excluded-target
      include: false
      source: false
    - pattern: included-source
      include: true
      source: true
  cancel_previous_builds: false  # Set to `true` to automatically cancel outdated webhook build